// Curated name -> icon map for content-authored icon references (InfoCardBlock.icon).
// Kept as an explicit allowlist (rather than importing the whole lucide-react namespace)
// so authored content can only reference icons we've deliberately included.
import {
  Sparkles,
  Brain,
  Cpu,
  Network,
  Layers3,
  Zap,
  Target,
  ShieldAlert,
  ShieldCheck,
  Scale,
  Eye,
  EyeOff,
  Lightbulb,
  BookOpen,
  Mail,
  FileText,
  Presentation,
  MessageSquare,
  Bot,
  Gem,
  Workflow,
  Share2,
  Image as ImageIcon,
  PenLine,
  GaugeCircle,
  TrendingUp,
  Users,
  Building2,
  Globe,
  Lock,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Rocket,
  DollarSign,
  Clock,
  Database,
  Code2,
  Wand2,
  ScanFace,
  Fingerprint,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  Sparkles,
  Brain,
  Cpu,
  Network,
  Layers3,
  Zap,
  Target,
  ShieldAlert,
  ShieldCheck,
  Scale,
  Eye,
  EyeOff,
  Lightbulb,
  BookOpen,
  Mail,
  FileText,
  Presentation,
  MessageSquare,
  Bot,
  Gem,
  Workflow,
  Share2,
  Image: ImageIcon,
  PenLine,
  GaugeCircle,
  TrendingUp,
  Users,
  Building2,
  Globe,
  Lock,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Rocket,
  DollarSign,
  Clock,
  Database,
  Code2,
  Wand2,
  ScanFace,
  Fingerprint,
};

export function resolveIcon(name?: string): LucideIcon {
  if (!name) return Sparkles;
  return ICON_MAP[name] ?? Sparkles;
}
